version: '3.8'

services:
  linkedin-runner:
    container_name: linkedin-runner-dev
    image: rgs.flutter.wtf/linkedin-runner:dev
    shm_size: '2gb'
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - ERP_API_TOKEN=$ERP_API_TOKEN
      - ERP_HOST_URL=$ERP_HOST_URL
      - IPROYAL_HOST_URL=$IPROYAL_HOST_URL
      - IPROYAL_API_KEY=$IPROYAL_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - FIBERY_HOST_URL=$FIBERY_HOST_URL
      - FIBERY_TOKEN=$FIBERY_TOKEN
      - ACCOUNT_TYPE=$ACCOUNT_TYPE
      - DISPLAY=:1
    ports:
      - 5900:5900
    networks:
      - root_nginx
    volumes:
      - browser_data:/home/ubuntu/.config/google-chrome
    user: root 

volumes:
  browser_data:

networks:
  root_nginx:
    external: true