export const DECISION_MAKERS_EXCLUDING_KEYWORD = {
  content: /\bcontent\b/i,
  brand: /\bbrand\b/i,
  design: /\bdesign\b/i,
  mall: /\bmall\b/i,
  education: /\beducation\b/i,
  customer: /\bcustomer\b/i,
  account: /\baccount\b/i,
  relation: /\brelation\b/i,
  market: /\bmarket\b/i,
  store: /\bstore\b/i,
  human: /\bhuman\b/i,
  editor: /\beditor\b/i,
  sales: /\bsales\b/i,
  qa: /\bqa\b/i,
  hr: /\bhr\b/i,
} as const;
