import { DECISION_MAKERS_INCLUDING_KEYWORD } from './decision-makers-including-keyword';
import { DECISION_MAKERS_POSITION } from './decision-makers-position';

export const DECISION_MAKERS_POSITION_PRIORITY = {
  [DECISION_MAKERS_POSITION.founder]: [DECISION_MAKERS_INCLUDING_KEYWORD.founder],
  [DECISION_MAKERS_POSITION.coFounder]: [DECISION_MAKERS_INCLUDING_KEYWORD.coFounder],
  [DECISION_MAKERS_POSITION.chiefExecutive]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefExecutive.executive,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefExecutive.ceo,
  ],
  [DECISION_MAKERS_POSITION.chiefTechnology]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefTechnology.technology,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefTechnology.cto,
  ],
  [DECISION_MAKERS_POSITION.president]: [DECISION_MAKERS_INCLUDING_KEYWORD.president],
  [DECISION_MAKERS_POSITION.boardMember]: [DECISION_MAKERS_INCLUDING_KEYWORD.boardMember],
  [DECISION_MAKERS_POSITION.managingPartner]: [DECISION_MAKERS_INCLUDING_KEYWORD.managingPartner],
  [DECISION_MAKERS_POSITION.chiefInformation]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefInformation.information,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefInformation.cio,
  ],
  [DECISION_MAKERS_POSITION.chiefOperating]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefOperating.operating,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefOperating.coo,
  ],
  [DECISION_MAKERS_POSITION.chiefProduct]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefProduct.product,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefProduct.cpo,
  ],
  [DECISION_MAKERS_POSITION.chiefMarketing]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefMarketing.marketing,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefMarketing.cmo,
  ],
  [DECISION_MAKERS_POSITION.chiefGrowth]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefGrowth.growth,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefGrowth.cgo,
  ],
  [DECISION_MAKERS_POSITION.chiefLegal]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefLegal.legal,
    DECISION_MAKERS_INCLUDING_KEYWORD.chiefLegal.clo,
  ],
  [DECISION_MAKERS_POSITION.anyChief]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.anyChief.anyChief,
    DECISION_MAKERS_INCLUDING_KEYWORD.anyChief.anyCLevel,
  ],
  [DECISION_MAKERS_POSITION.vicePresident]: [
    DECISION_MAKERS_INCLUDING_KEYWORD.vicePresident.full,
    DECISION_MAKERS_INCLUDING_KEYWORD.vicePresident.short,
  ],
  [DECISION_MAKERS_POSITION.head]: [DECISION_MAKERS_INCLUDING_KEYWORD.head],
  [DECISION_MAKERS_POSITION.director]: [DECISION_MAKERS_INCLUDING_KEYWORD.director],
  [DECISION_MAKERS_POSITION.manager]: [DECISION_MAKERS_INCLUDING_KEYWORD.manager],
} as const;
