version: '3.8'

services:
  linkedin-runner:
    container_name: linkedin-runner-dev
    image: rgs.flutter.wtf/linkedin-runner:dev
    shm_size: '2gb'
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - IPROYAL_API_KEY=$IPROYAL_API_KEY
      - TEMPORAL_GRPC_ENDPOINT=$TEMPORAL_GRPC_ENDPOINT
      - TEMPORAL_API_KEY=$TEMPORAL_API_KEY
      - TEMPORAL_NAMESPACE=$TEMPORAL_NAMESPACE
      - TEMPORAL_TASK_QUEUE=$TEMPORAL_TASK_QUEUE
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_KEY=$AWS_SECRET_KEY
    ports:
      - 5900:5900
    volumes:
      - browser_data:/home/ubuntu/.config/google-chrome
    user: root

volumes:
  browser_data:
